### ISSUE TITLE
About this version of the game update -2HOL_v20309

### ISSUE THREAD

**Issue by yukisamo** [risvh/miniOneLifeCompile#8]
Hey there! I was wondering if you could help me out with updating our local server to match the latest game update. I've been following the instructions to build the local version, but I'm a bit stuck on how to sync it up with the new update. Could you give me some guidance on that?"

**Comment by risvh** [comment]
Do `git pull` in each of the repos OneLife, OneLifeData7 and minorGems. Then start from step 7 in https://github.com/risvh/miniOneLifeCompile#usage.
